apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    apps: nginx
spec:
  selector: 
    matchLabels:
      app: myapp
  replicas: 3
  template:
      metadata:
        name: myapp-prod
        labels:
          app: myapp
      spec:
        containers:
          - name: nginx
            image: nginx
  
  
